config/routes.rb
Ordermeal::Application.routes.draw do
  resources :orderlists

  match '/users/1', to: 'users#admin_show'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

   root :to => 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_carousel.html.erb
<div class="span8">
    <div id="myCarousel" class="carousel slide">
    <ul class="carousel-indicators" >
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    </ul>
    <!-- Carousel items -->
    <div class="carousel-inner">
    <div class="active item"><%=image_tag "1.jpg",size:"600x350"%></div>
    <div class="item"><%=image_tag "2.jpg",size:"600x350"%></div>
    <div class="item"><%=image_tag "3.jpg",size:"600x350"%></div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
</div>

app/views/static_pages/_loginside.html.erb
<div class="span4">


<div class="row">
  <div class="span3">
    <%= form_for(:session, url: sessions_path) do |f| %>

      <%= f.label "注册邮箱" %>
      <%= f.text_field :email %>

      <%= f.label "密码" %>
      <%= f.password_field :password %>

      
  </div>
  <div class="span3">
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= f.submit "登录", class: "btn btn-large btn-primary" %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      
    <% end %>
    <%=render "users/form"%>
  </div>
 
</div>

</div>

app/views/static_pages/about.html.erb
<% provide(:title, '关于') %>
<h1><%=yield(:title)%></h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1><%=yield(:title)%></h1>

app/views/static_pages/home.html.erb
<h1><%=yield(:title)%></h1>
<div class="row">
	<!-- 滚动墙 -->
	<%=render "carousel"%>
	<!-- 登录边栏 -->
	<%=render "loginside"%>


</div>
</div>
</div>
  