config/routes.rb
Ordermeal::Application.routes.draw do
  resources :orderlists

  match '/users/1', to: 'users#admin_show'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

   root :to => 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation,:tel,
                  :louhao,:jiqu,:fangjian,:zuoyou
  has_secure_password
  has_many :orderlists, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :louhao,presence:true
  validates :jiqu,presence:true
  validates :fangjian,presence:true
  validates :zuoyou,presence:true
  validates :tel,presence:true,length:{is:11},numericality:true

  private
  

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
    
end

app/models/users_helper.rb
def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  before_filter :signed_in_user, only: [:index,:edit, :update,:destroy]
  before_filter :correct_user,   only: [:edit, :update]
   before_filter :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @orderlists = @user.orderlists.paginate(page: params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    
  end

  # POST /users
  # POST /users.json
  def create
    @user=User.new(name:params[:name],password:params[:password],tel:params[:tel],
                  email:params[:email],password_confirmation:params[:password_confirmation],
                  louhao:params[:louhao],jiqu:params[:jiqu],fangjian:params[:fangjian],
                  zuoyou:params[:zuoyou])

    respond_to do |format|
      if @user.save
        sign_in @user
        flash[:success] = "欢迎登录"
        format.html { redirect_to @user, notice: '用户创建成功.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
 

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:success] = "更新个人资料成功"
        sign_in @user
        redirect_to @user
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  

 private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
    	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    	image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/users/_form.html.erb
<button href="#myModal" data-toggle="modal" class="btn btn-large btn-primary" type="button">注册</button>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 id="myModalLabel">用户注册</h3>
</div>

<div class="modal-body">
	<div class="span3">
	<%=form_tag('/users')%>
		<%=label_tag "姓名"%>
		<%=text_field_tag :name,params[:name],placeholder:"请输入您的大名"%>
		
		<%=label_tag "登录邮箱"%>
		<%=text_field_tag :email,params[:email],placeholder:"example@163.com"%>
		
		<%=label_tag "密码"%>
		<%=password_field_tag :password,params[:password],placeholder:"密码至少六位"%>
		
		<%=label_tag "确认密码"%>
		<%=password_field_tag :password_confirmation,params[:password_confirmation],placeholder:"请再次输入确认"%>		
		<%=label_tag "手机"%>
		<%=text_field_tag :tel,params[:tel],placeholder:18392130959,maxlength:11%>
	</div>	
	<div class="span3">
		<%=label_tag "楼号"%>
		<%=select_tag :louhao,options_for_select({"12#"=>"12#","13#"=>"13#"})%>
		
		<%=label_tag "区号"%>
		<%=select_tag :jiqu,options_for_select({"I"=>"I","II"=>"II"})%>

		<%=label_tag "房间"%>
		<%=text_field_tag :fangjian,params[:fangjian],placeholder:218%>
		
		<%=label_tag "小室"%>
		<%=select_tag :zuoyou,options_for_select({"左"=>"左","中"=>"中","右"=>"右"})%>
	
	</div>
	<div class="span1 offset1">
		<%=submit_tag "提交"%>
	</div>

</div>
<div class="modal-footer">
	
<button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
</div>
</div>

app/views/users/_user.html.erb
<% if current_user.admin? && !current_user?(user) %>
<h1>用户列表</h1>
<%= will_paginate %>
<table class="table table-bordered table-hover table-condensed">
  <tr>
    <th>姓名</th>
    <th>邮箱</th>
    <th>电话</th>
    <th colspan="4" >&nbsp;&nbsp;&nbsp;&nbsp;宿舍</th>
    <th></th>
    <th></th>
    <th></th>
    
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.tel %></td>
    <td><%= user.louhao %></td>
    <td><%= user.jiqu %></td>
    <td><%= user.fangjian %></td>
    <td><%= user.zuoyou %></td>
    
    <td><%= link_to '查看', user %></td>
    <td><%= link_to '编辑', edit_user_path(user) %></td>
    <td><%= link_to '删除', user, method: :delete, data: { confirm: '确定删除吗?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate %>
<%= link_to '创建新用户', new_user_path %>

<% end %>

app/views/users/_user_list.html.erb
<div class="span8">
    <% if @user.orderlists.any? %>
      <h3>用户订单 (<%= @user.orderlists.count %>)</h3>
      <%=render "/orderlists/all_list"%>
      <%= will_paginate @orderlists %>
    <% end %>
</div>

app/views/users/admin_show.html.erb
<%=link_to "管理用户",users_path%>
<%=link_to "管理订单",orderlists_path%>

app/views/users/edit.html.erb
<h1>编辑</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label "姓名" %>
      <%= f.text_field :name %>

      <%= f.label "邮箱" %>
      <%= f.text_field :email %>

      <%= f.label "密码" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "确认密码" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "提交", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%=render 'user'%>

app/views/users/new.html.erb
<%= render 'form' %>

<%= link_to '返回', root_path %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside>
  	<%=@user.name%>
  	<%=@user.email%>
  	<%=@user.tel%>
  	<%=@user.louhao%>
  	<%=@user.jiqu%>
  	<%=@user.fangjian%>
  	<%=@user.zuoyou%>
  </aside>

  <%=render "user_list"%>
</div>