config/routes.rb
Ordermeal::Application.routes.draw do
  resources :orderlists

  match '/users/1', to: 'users#admin_show'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

   root :to => 'static_pages#home'

end

app/models/orderlist.rb
class Orderlist < ActiveRecord::Base
  attr_accessible :count, :hotel, :price, :taste
  belongs_to :user
  validates :user_id, presence: true
  validates :hotel,presence:true
  validates :taste,presence:true
  validates :count,numericality:true
  validates :price,numericality:true
  
end

app/controllers/orderlists_controller.rb
class OrderlistsController < ApplicationController
  # GET /orderlists
  # GET /orderlists.json
  def index
    @orderlists = Orderlist.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orderlists }
    end
  end

  # GET /orderlists/1
  # GET /orderlists/1.json
  def show
    @orderlist = Orderlist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @orderlist }
    end
  end

  # GET /orderlists/new
  # GET /orderlists/new.json
  def new
    @orderlist = Orderlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orderlist }
    end
  end

  # GET /orderlists/1/edit
  def edit
    @orderlist = Orderlist.find(params[:id])
  end

  # POST /orderlists
  # POST /orderlists.json
  def create
    @orderlist = Orderlist.new(params[:orderlist])

    respond_to do |format|
      if @orderlist.save
        format.html { redirect_to @orderlist, notice: 'Orderlist was successfully created.' }
        format.json { render json: @orderlist, status: :created, location: @orderlist }
      else
        format.html { render action: "new" }
        format.json { render json: @orderlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orderlists/1
  # PUT /orderlists/1.json
  def update
    @orderlist = Orderlist.find(params[:id])

    respond_to do |format|
      if @orderlist.update_attributes(params[:orderlist])
        format.html { redirect_to @orderlist, notice: 'Orderlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @orderlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderlists/1
  # DELETE /orderlists/1.json
  def destroy
    @orderlist = Orderlist.find(params[:id])
    @orderlist.destroy

    respond_to do |format|
      format.html { redirect_to orderlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orderlists_helper.rb
module OrderlistsHelper
end

app/views/orderlists/_all_list.html.erb
<h1>Listing orderlists</h1>

<%= will_paginate @orderlists %>
<table>
  <tr>
    <th>User</th>
    <th>Taste</th>
    <th>Count</th>
    <th>Price</th>
    <th>Hotel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orderlists.each do |orderlist| %>
  <tr>
    <td><%= orderlist.user_id %></td>
    <td><%= orderlist.taste %></td>
    <td><%= orderlist.count %></td>
    <td><%= orderlist.price %></td>
    <td><%= orderlist.hotel %></td>
    <td><%= link_to 'Show', orderlist %></td>
    <td><%= link_to 'Edit', edit_orderlist_path(orderlist) %></td>
    <td><%= link_to 'Destroy', orderlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @orderlists %>
<br />

<%= link_to 'New Orderlist', new_orderlist_path %>

app/views/orderlists/_form.html.erb
<%= form_for(@orderlist) do |f| %>
  <% if @orderlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orderlist.errors.count, "error") %> prohibited this orderlist from being saved:</h2>

      <ul>
      <% @orderlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :taste %><br />
    <%= f.text_field :taste %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :hotel %><br />
    <%= f.text_field :hotel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orderlists/edit.html.erb
<h1>Editing orderlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @orderlist %> |
<%= link_to 'Back', orderlists_path %>

app/views/orderlists/index.html.erb
<%=render "all_list"%>

app/views/orderlists/new.html.erb
<h1>New orderlist</h1>

<%= render 'form' %>

<%= link_to 'Back', orderlists_path %>

app/views/orderlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @orderlist.user_id %>
</p>

<p>
  <b>Taste:</b>
  <%= @orderlist.taste %>
</p>

<p>
  <b>Count:</b>
  <%= @orderlist.count %>
</p>

<p>
  <b>Price:</b>
  <%= @orderlist.price %>
</p>

<p>
  <b>Hotel:</b>
  <%= @orderlist.hotel %>
</p>


<%= link_to 'Edit', edit_orderlist_path(@orderlist) %> |
<%= link_to 'Back', orderlists_path %>