config/routes.rb
Ordermeal::Application.routes.draw do
  resources :orderlists

  match '/users/1', to: 'users#admin_show'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

   root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Xi Dian Ding Can</a>
    by Ferry Young
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于",   'about_path' %></li>
      <li><%= link_to "联系我们", 'contact_path#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "订餐", '/', id: "logo" %>
      <ul class="nav pull-right">
        <li class="divider-vertical"></li>
        
        <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                账户 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "个人中心", current_user %></li>
                <li><%= link_to "设置", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "退出", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "登录", signin_path %></li>
        <% end %>
         <li><%= link_to "帮助",help_path%></li>
        <li><%= link_to "关于", about_path %></li>
      </ul>
      <form class="navbar-search pull-right">
        <input type ="text" class="search-query" placeholder="找食儿">
      </form>
    </div>
  </div>  	
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=yield(:title)%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class="bodystyle">
    <%=render 'layouts/header'%>
	<div class ="container">
		<%= yield %>
	</div>
  <%=render "layouts/footer"%>
</body>
</html>